// Royal Oak open house listings.
// Edit this file to add/update/remove properties without touching the app markup.
// This is the master list of every home the app knows about. Each entry has a
// weekends array (which open-house weekend(s) it's assigned to; [] means the
// home hasn't been assigned to a weekend yet). WEEKENDS below just lists the
// known weekend ids/labels for the weekend dropdown in the app header.
let properties = [

  {
    id: "1", address: "915 E 6th St", city: "Royal Oak, MI", zip: "48067",
    lat: 42.4859548, lng: -83.1336454,
    priority: "⭐ Top", priorityGroup: "Top", priorityClass: "badge-top",
    day: "Sun", openHouse: "1:00–3:00 PM",
    price: "$475,000", rawPrice: 475000,
    beds: 5, baths: 2.0, sqft: "2,845", rawSqft: 2845,
    style: "Craftsman", isBungalow: false,
    notes: "Non-bungalow ✓. Just listed 7/22; confirm open time holds",
    yearBuilt: 1924,
    description: `Just a short walk from the heart of downtown Royal Oak, this beautifully updated 1920 home blends timeless character with the conveniences that are nearly impossible to find in a home of this era. With five bedrooms, a spacious walk-in closet in the primary suite, an attached garage, and the ultimate mudroom, it offers the charm of an established neighborhood without asking you to compromise on the features today's buyers want most. Top it all off with a private rooftop deck off the primary bedroom—the perfect place to enjoy your morning coffee or unwind after a long day.

Take a stroll downtown for dinner, grab coffee on Saturday mornings, or enjoy everything this vibrant community has to offer just minutes from your front door. Inside, you'll find generous living spaces filled with warmth and character, while thoughtful updates make everyday living feel effortless. The finished basement adds even more flexibility—whether you envision the ultimate movie room, home gym, playroom, office, or the perfect spot to gather for game day.

Homes like this don't come along often—a classic Royal Oak home that seamlessly combines historic charm with the modern conveniences buyers rarely find. If you've been waiting for a home that offers character, functionality, and an unbeatable location, this is it.`,
    url: "https://www.zillow.com/homedetails/915-E-6th-St-Royal-Oak-MI-48067/24648628_zpid/",
    weekends: ["jul24"],
  },
  {
    id: "2", address: "1029 Longfellow Ave", city: "Royal Oak, MI", zip: "48067",
    lat: 42.4808258, lng: -83.1342948,
    priority: "⭐ Top", priorityGroup: "Top", priorityClass: "badge-top",
    day: "Sun", openHouse: "2:00–4:00 PM",
    price: "$529,900", rawPrice: 529900,
    beds: 3, baths: 2.0, sqft: "2,230", rawSqft: 2230,
    style: "2-Story", isBungalow: false,
    notes: "Non-bungalow ✓. Strong match; 3D tour. Confirm Sun open house is active",
    yearBuilt: 1925,
    description: `ROYAL OAK HOME SHOPPERS, make sure to look at this beautiful Royal Oak Home which is a perfect combination of modern luxurious updates and timeless charm in an unbeatable location! Just steps from Lawson Park, perfect for children and teens, and even closer to Franklin Park, which is just a corner away, offering free Tennis courts, and only a short walk away from downtown Royal Oak, where you can enjoy shopping, the Royal Oak Farmers Market, movie theaters and theaters, bars, restaurants and so much more. You can even walk to the Detroit Zoo! Besides the amazing location, this residence will be a happy place, completely updated with high-quality upgrades, including energy-efficient windows, new siding, and gutters, blinds, ring camera, new flooring, painting, HVAC ultraviolet light air purifier, light fixtures, and many more completing an entire renovation. A spacious main level welcomes you with high ceilings and lots of natural light. The inviting living room features a cozy fireplace and a stylish built-in bar area, perfect for entertaining and full of character. The formal dining room is very spacious and sourounded with windows. The modern classy kitchen with brand-new stainless steel appliances, a gas range, quartz countertops, and custom cabinetry offers elegance and functionality with high end materials. The convenient main-floor laundry room and full bath with a sleek walk-in shower add everyday ease. On the second floor you'll find three generously sized bedrooms with good closet space, along with a beautiful and classy updated full bathroom. The finished lower level provides versatile additional living space—ideal for a home theater, fitness area, or recreation room. Enjoy a beautiful fenced in backyard perfect for entertaining, relaxing, gardening or play, along with a detached two-car garage. Another highlight of the home is the beautiful modern season's room welcoming to the home and adding additional sqf for home living quality. Entire Ring system incl.`,
    url: "https://www.zillow.com/homedetails/1029-Longfellow-Ave-Royal-Oak-MI-48067/24649120_zpid/",
    weekends: ["jul24"],
  },
  {
    id: "12", address: "116 S Kenwood Ave", city: "Royal Oak, MI", zip: "48067",
    lat: 42.4897798, lng: -83.1214001,
    priority: "⭐ Top", priorityGroup: "Top", priorityClass: "badge-top",
    day: "Sun", openHouse: "1:00–3:00 PM",
    price: "$489,000", rawPrice: 489000,
    beds: 3, baths: 2.0, sqft: "2,050", rawSqft: 2050,
    style: "Traditional", isBungalow: false,
    notes: "Non-bungalow ✓. Near Downtown Royal Oak; Sunday open house.",
    yearBuilt: 1923,
    description: `Welcome to this charming 1923 three-bedroom, one-and-a-half-bath brick and wood Tudor offering over 1,500 square feet just minutes from downtown Royal Oak. Enter through the arched front door into a welcoming foyer with basketweave tile, then step into the inviting living room featuring a wood-burning fireplace, large crown molding, and hardwood floors throughout. The living room flows into the formal dining room, which leads into the kitchen featuring white cabinetry, dark countertops, generous storage, a gas stove, and stainless steel appliances, including a newer refrigerator and dishwasher. The first floor also offers a home office, a convenient half bath with wainscoting, and a bright four-season room overlooking the fenced backyard. Upstairs, you'll find three spacious bedrooms and a full bath. The unfinished basement provides extra storage and potential for additional living space. Recent updates include a roof (approximately 9 years old), an electrical panel (updated 4 years ago), a new sewer liner with a 50-year warranty (May 2026), and a new sewer cleanout. Outside, enjoy a patio, fenced backyard, and detached 2.5-car garage. Don't miss your opportunity to own this timeless Royal Oak Tudor.`,
    url: "https://www.zillow.com/homedetails/116-S-Kenwood-Ave-Royal-Oak-MI-48067/24650296_zpid/",
    weekends: ["jul24"],
  },
  {
    id: "19", address: "1102 N Lafayette Ave", city: "Royal Oak, MI", zip: "48067",
    lat: 42.4989454, lng: -83.1480093,
    priority: "⭐ Top", priorityGroup: "Top", priorityClass: "badge-top",
    day: "Sun", openHouse: "1:00–3:00 PM",
    price: "$498,000", rawPrice: 498000,
    beds: 3, baths: 2.0, sqft: "2,120", rawSqft: 2120,
    style: "Craftsman", isBungalow: false,
    notes: "Non-bungalow ✓. Prime Lafayette corridor location; Sunday open house.",
    yearBuilt: 1949,
    description: `Introducing an exceptional opportunity to own this charming brick bungalow in the heart of Royal Oak, offering nearly 1,700 square feet of living space and an unbeatable location just moments from Downtown Royal Oak. Combining timeless character, spacious living areas, and everyday convenience, this home provides the perfect blend of comfort and lifestyle. Upon entry, you are welcomed by beautiful hardwood floors, abundant natural light from plantation shutters, and a warm, inviting atmosphere. The spacious living room is anchored by a charming fireplace, creating the perfect setting for relaxing. The adjoining cozy dining area flows seamlessly into the galley kitchen, featuring stainless steel appliances, a Viking gas range, Viking wine cooler, generous cabinetry, and functional workspace. The main level offers two spacious bedrooms and a full bathroom, while the upper level serves as a private primary retreat featuring a spacious bedroom, full bathroom, skylights, French doors, custom window treatments, and a flexible loft area filled with natural light. The oversized primary bathroom features a whirlpool tub and separate shower. French doors open to a private upper level deck overlooking the backyard, offering the perfect place to relax and unwind. Outside, enjoy a rare oversized double lot with a fully fenced backyard offering exceptional privacy and outdoor space seldom found this close to Downtown Royal Oak. A spacious deck creates the perfect setting for outdoor dining and summer gatherings, while the detached one car detached garage provides added convenience. The basement offers abundant storage and outstanding potential for future finishing, creating opportunities for additional living space. Located within walking distance of Downtown Royal Oak and just minutes from premier dining, shopping, parks, schools, and major commuter routes, this home offers the ideal combination of location, charm, and functionality, Welcome Home!`,
    url: "https://www.zillow.com/homes/1102-N-Lafayette-Ave-Royal-Oak,-MI-48067_rb/",
    weekends: ["jul24"],
  },
  {
    id: "13", address: "827 Gardenia Ave", city: "Royal Oak, MI", zip: "48067",
    lat: 42.4981495, lng: -83.1348984,
    priority: "⭐ Good", priorityGroup: "Good", priorityClass: "badge-good",
    day: "Sun", openHouse: "12:00–2:00 PM",
    price: "$415,000", rawPrice: 415000,
    beds: 3, baths: 2.0, sqft: "1,820", rawSqft: 1820,
    style: "Craftsman", isBungalow: false,
    notes: "Non-bungalow ✓. Updated interior; Sunday open house.",
    yearBuilt: 1923,
    description: `Some homes ask you to choose between city energy and quiet nights in. This one in Royal Oak does not. A short walk brings you into the restaurants, coffee shops, and steady weekend activity that make downtown Royal Oak one of the most searched neighborhoods in Metro Detroit. Head back and the pace changes. A patio sits off the back of the home, a natural fire pit anchors the yard, and the primary bedroom has been renovated into an ensuite. This three bedroom, two bathroom bungalow was fully renovated with a new kitchen, floors, roof, and plumbing, and the basement is waterproofed with a warranty. A smart washer and dryer tower has been added, and the home has been freshly painted throughout. You're positioned minutes from major highways, putting most places in the Metro Detroit area about 20 minutes away, including Downtown Detroit. It is a rare combination in Royal Oak, walkable to everything downtown offers, and quiet enough to feel completely removed from it.`,
    url: "https://www.zillow.com/homes/827-Gardenia-Ave-Royal-Oak,-MI-48067_rb/",
    weekends: ["jul24"],
  },
  {
    id: "15", address: "1207 Irving Ave", city: "Royal Oak, MI", zip: "48067",
    lat: 42.4795034, lng: -83.135392,
    priority: "⭐ Good", priorityGroup: "Good", priorityClass: "badge-good",
    day: "Sun", openHouse: "1:00–3:00 PM",
    price: "$450,000", rawPrice: 450000,
    beds: 3, baths: 2.0, sqft: "1,950", rawSqft: 1950,
    style: "2-Story", isBungalow: false,
    notes: "Non-bungalow ✓. Added Sunday open house schedule.",
    yearBuilt: 1927,
    description: `Exceptional Colonial Just Moments from Downtown Royal Oak! From the moment you arrive, this charming, updated Colonial captivates with its lush perennial landscaping and standout curb appeal. Step inside to discover an inviting layout that seamlessly blends classic architectural details, coved ceilings, graceful arched doorways, and gorgeous oak hardwood floors, with modern upgrades. The sun-drenched living room serves as a cozy focal point, featuring a natural fireplace framed by elegant beveled windows. Gather in the formal dining room surrounded by walls of windows, or utilize the main-level bonus room as a quiet home office or a 4th bedroom! The heart of the home is a bright, spacious kitchen equipped with stainless steel appliances, a deep undermount stainless sink, timeless oak cabinetry, a planter-box window, a charming beadboard ceiling, and abundant counter space. A doorwall off the kitchen leads directly out to the back deck for seamless indoor-outdoor living. Upstairs, the second level hosts three generously sized bedrooms and a completely renovated full bath complete with a dual quartz-topped vanity and a luxurious Mr. Steam Euro-shower. Need even more space? The dry, finished basement adds valuable living area with a cozy family room, an impressive second full bath, a dedicated utility/storage area, and privacy glassblock windows. Out back, entertain effortlessly in the deep, fully fenced backyard anchored by a detached 2-car garage. Unbeatable location - enjoy quick access to Downtown Royal Oak's premier dining, shopping, and nightlife, with effortless commutes via I-75, Woodward, and Corewell Health (Beaumont). This exceptional property won't last long... schedule your tour today!`,
    url: "https://www.zillow.com/homes/1207-Irving-Ave-Royal-Oak,-MI-48067_rb/",
    weekends: ["jul24"],
  },
  {
    id: "18", address: "2436 N Vermont Ave", city: "Royal Oak, MI", zip: "48073",
    lat: 42.5114021, lng: -83.1291263,
    priority: "Good", priorityGroup: "Good", priorityClass: "badge-good",
    day: "Sun", openHouse: "2:00–4:00 PM",
    price: "$439,000", rawPrice: 439000,
    beds: 3, baths: 2.0, sqft: "1,880", rawSqft: 1880,
    style: "Split-Level", isBungalow: false,
    notes: "Non-bungalow ✓. Sunday open house scheduled.",
    yearBuilt: 1948,
    description: `Welcome to this meticulously maintained brick bungalow in the heart of Royal Oak, perfectly positioned across from Red Run Golf Club. One of this home's greatest advantages is the peace of mind that comes with its major improvements. Featuring a newer roof, newer windows, a beautifully finished basement (2021), and a newly built garage (2021), many of the costly updates have already been completed for you! Offering 3 bedrooms, 2 full bathrooms, and timeless charm throughout, this move-in-ready home seamlessly blends character, comfort, and modern updates. The thoughtfully designed kitchen serves as the heart of the home, providing a functional and inviting space for everyday living and entertaining. The remodeled main-floor bathroom adds style and convenience, while the welcoming family room features a cozy wood-burning fireplace, creating the perfect gathering space. Two bedrooms with beautiful hardwood floors are located on the main level, while the spacious upstairs bedroom offers privacy and abundant closet space. The finished lower level provides valuable additional living space and features a full bathroom, laundry area, and flexible space perfect for a recreation room, home office, or gym. Step outside to your private backyard retreat, complete with a patio ideal for entertaining, relaxing, or enjoying warm summer evenings. The newer 2.5-car garage includes a dedicated workshop area, offering plenty of room for hobbies, storage, and projects. Minutes from downtown Royal Oak and downtown Berkley and within walking distance to Red Run park. With numerous updates, and pride of ownership evident throughout, this exceptional home offers a rare opportunity to enjoy the highly desirable Royal Oak lifestyle in a truly turnkey setting.`,
    url: "https://www.zillow.com/homes/2436-N-Vermont-Ave-Royal-Oak,-MI-48073_rb/",
    weekends: ["jul24"],
  },
  {
    id: "17", address: "3210 Harvard Rd", city: "Royal Oak, MI", zip: "48073",
    lat: 42.513071, lng: -83.1968004,
    priority: "⭐ Top", priorityGroup: "Top", priorityClass: "badge-top",
    day: "Sun", openHouse: "1:00–4:00 PM",
    price: "$520,000", rawPrice: 520000,
    beds: 4, baths: 2.5, sqft: "2,300", rawSqft: 2300,
    style: "Colonial", isBungalow: false,
    notes: "Non-bungalow ✓. Quiet neighborhood setting; Sunday open house.",
    yearBuilt: 1920,
    description: `Thoughtfully rebuilt and expanded in 2021 by John Graham, this 3-bedroom, 2.1-bathroom home offers over 3,000 square feet of total finished living space, including a finished basement completed in 2023. Situated on a professionally landscaped lot and just a short walk to downtown Berkley, the home combines modern design with everyday functionality. The open-concept main level features recessed lighting, crown moulding, and a beautifully appointed kitchen with granite-topped shaker cabinetry, stainless steel appliances, and a large island with seating. The dining area opens to a custom stone-paver patio and private fenced backyard, creating seamless indoor-outdoor living. The first-floor primary suite offers a spacious walk-in closet and an updated bath with dual vanities and an oversized tiled shower. Upstairs are two additional bedrooms with walk-in closets, a full bath, and second-floor laundry. The finished lower level adds exceptional versatility with a built-in bar and ample space for entertaining, recreation, or a home office. Additional highlights include zoned heating and cooling with two furnaces and two air-conditioning units, and an attached oversized two-car garage. Ideally located between Royal Oak and Berkley, this move-in-ready home offers space, style, and a highly desirable walkable lifestyle.`,
    url: "https://www.zillow.com/homes/3210-Harvard-Rd-Royal-Oak,-MI-48073_rb/",
    weekends: ["jul24"],
  },
  {
    id: "14", address: "2925 Bembridge Rd", city: "Royal Oak, MI", zip: "48073",
    lat: 42.5136336, lng: -83.1799036,
    priority: "⭐ Top", priorityGroup: "Top", priorityClass: "badge-top",
    day: "Sun", openHouse: "2:00–4:00 PM",
    price: "$545,000", rawPrice: 545000,
    beds: 4, baths: 2.5, sqft: "2,450", rawSqft: 2450,
    style: "Colonial", isBungalow: false,
    notes: "Non-bungalow ✓. Spacious layout in North Royal Oak; Sunday open house.",
    yearBuilt: 1948,
    description: `Welcome to this beautifully maintained Royal Oak bungalow offering a bright, open floor plan, stunning hardwood floors, an updated open kitchen, and a partially finished basement. The inviting living room features coved ceilings, recessed lighting, and a charming gas fireplace, flowing seamlessly into the central dining room with French doors opening to the enclosed 3 seasons back porch with built-in seating.

The kitchen door was expanded showcasing white cabinetry, granite countertops, and a timeless subway tile backsplash. Two main-floor bedrooms include pristine hardwood floors, large closets, along with a full bath conveniently located off the hallway.

Upstairs, you'll find the hallway has abundant built-in storage, two additional bedrooms with generous closet space, and a second full bath. One bedroom can serve as a home office or playroom. The finished basement offers flexible living space, separate laundry, and plenty of additional storage, adding to the home's functionality and versatility.

Outside, enjoy exceptional curb appeal with attractive landscaping, a welcoming covered front porch, recently installed gutter guards, irrigation in both the front and back yards, a large fenced backyard, patio and a two-car garage. Ideally situated just a short distance to neighborhood parks and the shopping, dining, and entertainment along Woodward Avenue.

This move-in-ready, turnkey home perfectly blends classic bungalow charm with modern updates in a highly desirable Royal Oak location. Welcome Home!`,
    url: "https://www.zillow.com/homedetails/2925-Bembridge-Rd-Royal-Oak-MI-48073/24621416_zpid/",
    weekends: ["jul24"],
  },
  {
    id: "3", address: "3803 Linwood Ave", city: "Royal Oak, MI", zip: "48073",
    lat: 42.522238, lng: -83.1712361,
    priority: "⭐ Good", priorityGroup: "Good", priorityClass: "badge-good",
    day: "Sat", openHouse: "12:00–2:00 PM",
    price: "$598,900", rawPrice: 598900,
    beds: 3, baths: 3.0, sqft: "2,741", rawSqft: 2741,
    style: "Colonial", isBungalow: false,
    notes: "Non-bungalow ✓ (Realtor.com mistags 'bungalow'). Top of budget.",
    yearBuilt: 1954,
    description: `Welcome to this fully updated 3 bedroom, 3 Bath home with outstanding curb appeal! Dream kitchen w/ SS appliances, double oven, gas range, plenty of cabinets, quartz countertops w/ breakfast bar seating. Recess lighting and hardwood floors throughout. Large bedrooms w/ additional family room w/ door to your private backyard. Spacious and amazing upper primary bedroom w/ attached bathroom w/ dual vanities and Euro shower. 2 huge walk-in closets w/ additional linen closet. Natural light throughout. Finished LL w/ 3rd bathroom. 1 1/2 car garage. Sleek exterior fencing. Sit back and enjoy the cement patio surrounded w/ beautiful landscaping, your private oasis! Walk to Normandy Oaks Park. Close to Freeways, Restaurants and Shopping. BATVIA`,
    url: "https://www.zillow.com/homedetails/3803-Linwood-Ave-Royal-Oak-MI-48073/24616754_zpid/",
    weekends: ["jul24"],
  },
  {
    id: "4", address: "4518 Woodland Ave", city: "Royal Oak, MI", zip: "48073",
    lat: 42.5302046, lng: -83.1702831,
    priority: "Good", priorityGroup: "Good", priorityClass: "badge-good",
    day: "Sat", openHouse: "1:00–4:00 PM",
    price: "$400,000", rawPrice: 400000,
    beds: 4, baths: 2.0, sqft: "1,530", rawSqft: 1530,
    style: "Colonial / 1.5-story", isBungalow: false,
    notes: "STYLE CONFLICT: Zillow=Colonial, Trulia=Bungalow. Verify style + south of 14 Mile",
    yearBuilt: 1955,
    description: `Welcome to this classic 4-bedroom, 2-bathroom home designed for comfort and flexibility! Featuring two spacious bedrooms on the main level and two upstairs, plus a full bathroom on each floor, this functional layout offers ideal versatility for any living arrangement. Inside, beautiful floors flow through bright, inviting living spaces. Unwind in the bright back sunroom, which offers serene views of your expansive backyard—a perfect backdrop for outdoor entertaining, gardening, and play. Downstairs, the full basement provides exceptional potential for additional storage, a home workshop, or a future recreation space. Parking and extra storage are a breeze with the 2-car garage. With its great layout, generous outdoor space, and timeless charm, this home is ready for its next owner. Schedule your private showing today and experience all it has to offer!`,
    url: "https://www.zillow.com/homedetails/4518-Woodland-Ave-Royal-Oak-MI-48073/24615972_zpid/",
    weekends: ["jul24"],
  },
  {
    id: "5", address: "305 Devillen Ave", city: "Royal Oak, MI", zip: "48073",
    lat: 42.5156591, lng: -83.1419875,
    priority: "Verify", priorityGroup: "Verify", priorityClass: "badge-verify",
    day: "Sat/Sun", openHouse: "Sat 12–2 / Sun 1–3",
    price: "$319,900", rawPrice: 319900,
    beds: 3, baths: 2.0, sqft: "1,733", rawSqft: 1733,
    style: "BUNGALOW", isBungalow: true,
    notes: "⚠️ Listed as a bungalow — excludes per your criteria. Under budget",
    yearBuilt: 1948,
    description: `Welcome to one of Royal Oak's most beautifully updated bungalows in a very desirable neighborhood. Featuring three bedrooms, two full baths. The entire house has been tastefully updated with new kitchen cabinets, quartz countertops, backsplash, stainless steel appliances and fixtures. Both bathrooms have been redesigned with new tiles, vanities and fixtures. Beautiful hardwood floors throughout accented with all new base molding. New paint throughout. Finished basement with a full bath. Brand new A/C for your comfort and convenience. New sewer line installed in 2024. The backyard is fully fenced with a large 2 1/2 car garage. Short walk to Oak Ridge Elementary, McDonald's and Dairy Queen. The house is a must see.`,
    url: "https://www.zillow.com/homedetails/305-Devillen-Ave-Royal-Oak-MI-48073/24624924_zpid/",
    weekends: ["jul24"],
  },
  {
    id: "6", address: "1616 N Vermont Ave", city: "Royal Oak, MI", zip: "48067",
    lat: 42.5037065, lng: -83.129134,
    priority: "Verify", priorityGroup: "Verify", priorityClass: "badge-verify",
    day: "Sun", openHouse: "2:00–4:00 PM",
    price: "$360,000", rawPrice: 360000,
    beds: 3, baths: 2.0, sqft: "1,720", rawSqft: 1720,
    style: "BUNGALOW", isBungalow: true,
    notes: "⚠️ Architectural style = Bungalow — excludes per criteria.",
    yearBuilt: 1941,
    description: `Welcome to this beautifully updated 3-bedroom, 2 full-bath home in the heart of Royal Oak! Full of character and charm, this home perfectly blends timeless details with modern updates. The spacious upstairs primary suite offers a private retreat with a large walk-in closet, while both bathrooms have been beautifully renovated with stylish finishes. The extra-spacious kitchen is perfect for everyday living and entertaining, featuring a brand-new kitchen appliance package and plenty of cabinet and counter space. Additional highlights include a detached 1.5-car garage, numerous thoughtful updates, and true turnkey convenience. Perfect for first-time buyers or anyone looking to move right in and enjoy all that Royal Oak has to offer, just minutes from downtown dining, shopping, and entertainment.`,
    url: "https://www.zillow.com/homedetails/1616-N-Vermont-Ave-Royal-Oak-MI-48067/24634323_zpid/",
    weekends: ["jul24"],
  },
  {
    id: "7", address: "1815 Massoit Rd", city: "Royal Oak, MI", zip: "48073",
    lat: 42.5285831, lng: -83.1665443,
    priority: "Verify", priorityGroup: "Verify", priorityClass: "badge-verify",
    day: "Sat", openHouse: "12:00–2:00 PM",
    price: "$345,000", rawPrice: 345000,
    beds: 3, baths: 1.5, sqft: "2,100", rawSqft: 2100,
    style: "Ranch", isBungalow: false,
    notes: "Non-bungalow ✓ but only 1,426 sq ft ABOVE grade.",
    yearBuilt: 1958,
    description: `Open house! Saturday, July 25th from 12pm-2pm. Royal Oak's leading home seller presents this classic brick ranch that pairs timeless character with easy everyday comfort, offering three bedrooms, one and a half baths, a sunny back family room, and a fenced yard made for entertaining. Step inside to a bright entry living room anchored by a large bay window. The layout carries into a central kitchen and dining area with generous cabinet space. Just beyond, the back family room features warm wood paneling, a cozy brick fireplace, and a sliding glass door that opens to the backyard. Three nice sized bedrooms share a full bath down the hallway. Downstairs, the partially finished basement adds valuable extra space with a half bath, laundry, and plenty of storage. Out back, the fenced yard offers room to gather along with a detached two car garage. ORIGINAL owner and first time ever on the market! Welcome Home!`,
    url: "https://www.zillow.com/homedetails/1815-Massoit-Rd-Royal-Oak-MI-48073/24616115_zpid/",
    weekends: ["jul24"],
  },
  {
    id: "8", address: "309 Amelia Ave", city: "Royal Oak, MI", zip: "48073",
    lat: 42.5188, lng: -83.1531,
    priority: "Verify", priorityGroup: "Verify", priorityClass: "badge-verify",
    day: "—", openHouse: "None this wknd?",
    price: "$469,900", rawPrice: 469900,
    beds: 4, baths: 1.5, sqft: "2,180", rawSqft: 2180,
    style: "Colonial", isBungalow: false,
    notes: "⚠️ Open houses were last wknd. Confirm if re-listed.",
    yearBuilt: 1967,
    description: `Beautiful Park like setting on beautiful fenced treed lot in North Royal Oak. Beautiful public park just down the road and easy access to Clawson and Birmingham. This spacious home is beautifully updated with a brand-new kitchen with stainless appliances, new granite counters and new laminate flooring. There is newer carpet on the main level and beautiful hardwood floors on the second level. The home interior has been freshly painted and there is a formal dining room, family room with natural fireplace, 3 season sunroom, and extra living space and storage in the finished basement. The large back yard has a beautiful paver brick patio and a garden shed for all of the lawn tools. The home offers a large covered front porch, attached garage, and underground sprinklers.`,
    url: "https://www.zillow.com/homedetails/309-Amelia-Ave-Royal-Oak-MI-48073/24612671_zpid/",
    weekends: ["jul24"],
  },
  {
    id: "16", address: "223 N Alexander Ave", city: "Royal Oak, MI", zip: "48067",
    lat: 42.491766, lng: -83.1342585,
    priority: "Verify", priorityGroup: "Verify", priorityClass: "badge-verify",
    day: "Sun", openHouse: "12:00–2:00 PM",
    price: "$350,000", rawPrice: 350000,
    beds: 3, baths: 1.5, sqft: "1,600", rawSqft: 1600,
    style: "BUNGALOW", isBungalow: true,
    notes: "⚠️ Architectural style = Bungalow — excludes per criteria.",
    yearBuilt: 1939,
    description: `Quality workmanship in this newly updated bungalow by Farhat Family Homes! Located in the heart of downtown Royal Oak, just steps from Whittier Park, this home blends timeless charm with modern updates. The maintenance free exterior features an oversized covered front porch, mature landscaping w irrigation, front and rear lighting and a detached 2 car garage. Exterior updates include roof, windows, siding, gutters, gutter guards, garage door with opener, exterior doors, privacy fence and driveway. Step inside to the warm and inviting living room filled with natural light that seamlessly flows into the dining area. Newly refinished hardwood floors throughout creating an ideal layout for everyday living and entertaining. The updated kitchen features soft closing custom cabinetry, quartzite countertops, tile backsplash, under cabinet lighting, and Frigidaire Pro stainless steel appliances including 6 burner stove w hood fan and drawer microwave. Two bedrooms and a thoughtfully remodeled full bath complete the main level. Upstairs, you'll find a private primary retreat featuring vaulted ceilings, recessed lighting, an amazing walk-in-closet, and plenty of room for a sitting area or desk/vanity. The finished basement features a full bath with tile shower, an additional living space for entertaining, a proper laundry area with front load washer/dryer included, and mudroom lockers with additional built ins. Large storage room for all your needs. Step outside to the oversized newly refinished deck and private backyard with plenty of space to host or enjoy outdoor activities. All new mechanicals including furnace, water tank, AC, electrical and plumbing. Additional updates include all high end plumbing and electrical fixtures, refinished hardwood floors, and new trim and solid wood doors throughout. New security system included. No expense spared. Agent owned.`,
    url: "https://www.zillow.com/homes/223-N-Alexander-Ave-Royal-Oak,-MI-48067_rb/",
    weekends: ["jul24"],
  },
  {
    id: "w0710-1", address: "707 S Laurel St", city: "Royal Oak, MI", zip: "48067",
    lat: 42.4843144, lng: -83.1497468,
    priority: "Verify", priorityGroup: "Verify", priorityClass: "badge-verify",
    day: "—", openHouse: "Not yet scheduled",
    price: "$525,000", rawPrice: 525000,
    beds: 3, baths: 2.5, sqft: "1,781", rawSqft: 1781,
    style: "Colonial", isBungalow: false,
    notes: "",
    yearBuilt: 1919,
    description: `Unbeatable location meets expansive layout in the heart of Downtown Royal Oak! Beautifully renovated in 2018, this stunning 3-bedroom, 2.5-bathroom Colonial offers an impressive 1,787 sq. ft. of finished living space- a rare footprint for downtown living. From the moment you step onto the welcoming, deep covered front porch, you will fall in love with the high-end architectural details, including custom crown molding, large baseboards, and elegant trim work throughout. The bright, open-concept living area features recessed lighting, immaculate wood floors, and a gorgeous floor-to-ceiling stone fireplace flanked by custom built-ins. The gourmet white kitchen is an entertainer's dream, complete with premium granite countertops, stainless steel appliances, a beautiful glass backsplash, and a convenient breakfast bar. Upstairs, the main bathroom features a dual vanity with granite counters. The luxurious primary suite serves as your private oasis, boasting a dual vanity, a custom Euro-style shower, and a private water closet. Enjoy the absolute convenience of a first-floor laundry room and find an abundance of storage space in the full basement. Outside, a large deck opens off the back of the house, overlooking a spacious, fully fenced-in backyard alongside an oversized 2-car detached garage. Perfectly situated on a beautiful, tree-lined street, you are just minutes away from downtown Royal Oak, giving you instant access to vibrant dining, boutique shopping, and endless entertainment. Don't miss the chance to own this exceptional gem, it won't last! Call for a private tour today!`,
    url: "https://www.zillow.com/homedetails/707-S-Laurel-St-Royal-Oak-MI-48067/24647182_zpid/",
    mlsListingId: "20261045786",
    weekends: ["jul10"],
  },
  {
    id: "w0710-2", address: "10504 Borgman Ave", city: "Huntington Woods, MI", zip: "48070",
    lat: 42.4867943, lng: -83.1687318,
    priority: "Verify", priorityGroup: "Verify", priorityClass: "badge-verify",
    day: "—", openHouse: "Visited 7/10–7/12 weekend",
    price: "$539,000", rawPrice: 539000,
    beds: 3, baths: 2.0, sqft: "1,761", rawSqft: 1761,
    style: "N/A", isBungalow: false,
    notes: "Visited during the July 10–12 weekend. Details TBD.",
    yearBuilt: null,
    description: "",
    url: "https://www.zillow.com/homes/10504-Borgman-Ave-Huntington-Woods,-MI-48070_rb/",
    weekends: ["jul10"],
  },
  {
    id: "w0710-3", address: "13154 Lasalle Blvd", city: "Huntington Woods, MI", zip: "48070",
    lat: 42.4872399, lng: -83.1803817,
    priority: "Verify", priorityGroup: "Verify", priorityClass: "badge-verify",
    day: "—", openHouse: "Visited 7/10–7/12 weekend",
    price: "$449,000", rawPrice: 449000,
    beds: 3, baths: 2.0, sqft: "2,450", rawSqft: 2450,
    style: "N/A", isBungalow: false,
    notes: "Visited during the July 10–12 weekend. Details TBD.",
    yearBuilt: null,
    description: "",
    url: "https://www.zillow.com/homes/13154-Lasalle-Blvd-Huntington-Woods,-MI-48070_rb/",
    weekends: ["jul10"],
  },
  {
    id: "w0710-4", address: "908 Marywood Dr", city: "Royal Oak, MI", zip: "48067",
    lat: 42.4966928, lng: -83.1490077,
    priority: "Verify", priorityGroup: "Verify", priorityClass: "badge-verify",
    day: "—", openHouse: "Not yet scheduled",
    price: "$495,000", rawPrice: 495000,
    beds: 3, baths: 2, sqft: "2,024", rawSqft: 2024,
    style: "Contemporary", isBungalow: false,
    notes: "",
    yearBuilt: 1961,
    description: `Spacious and gracious w/ a BRAND NEW ROOF INSTALLED JUNE 2026!, 916 Marywood offers something different, something special. This spacious contemporary style quad level home is located within true walking distance of downtown Royal Oak. (with all of its year round shopping, restaurant's, & festivals), Meininger Park is around the corner,& public fields & courts abound nearby. Inside, the main living room is a large, bright, modern space w/ recessed lighting & rich, dark hardwood floors. The kitchen is perfectly set up for cooking & social enjoyment w/ expansive counter space, stainless steel appliances inc. space saving microwave, lots of cupboards & storage. The large eating area is highlighted by a bay window to the rear. There is a family room w/ a natural fireplace, custom built in bookshelves, & a library type feel. The first full bath featuring slate accents is located off the family room. The laundry room is bright & roomy w/storage, shelving & direct outside access. The upper level holds all 3 bedrooms (featuring large closets & hardwood floors), & an updated, second full bath. The lower level has been divided into an awesome home gym, a great unfinished storage area, & furnace/utility room. The large, private yard feat. a covered patio area that provides a great entertainment space, the large 2 car garage will protect from the elements, This house can help you get more out of life. Marywood is a wonderful street, this home is updated, (windows, HVAC, etc) special, & ready for you to Make Home Here.`,
    url: "https://www.zillow.com/homedetails/908-Marywood-Dr-Royal-Oak-MI-48067/24637916_zpid/",
    mlsListingId: "20261039009",
    weekends: ["jul10"],
  },
  {
    id: "w0710-5", address: "1036 Irving Ave", city: "Royal Oak, MI", zip: "48067",
    lat: 42.4805839, lng: -83.1359686,
    priority: "Verify", priorityGroup: "Verify", priorityClass: "badge-verify",
    day: "—", openHouse: "Not yet scheduled",
    price: "$479,900", rawPrice: 479900,
    beds: 3, baths: 1.5, sqft: "1,714", rawSqft: 1714,
    style: "Dutch Colonial", isBungalow: false,
    notes: "",
    yearBuilt: 1924,
    description: `PRICE IMPROVEMENT – NOW OFFERED AT $479,900! Just steps from vibrant Downtown Royal Oak, this beautifully updated Dutch Colonial blends timeless character with thoughtful modern upgrades. Featuring 3 bedrooms, 2 full bathrooms, and an exceptional layout, this home offers the perfect balance of charm, functionality, and style. The remodeled designer kitchen has top of the line appliances, modern finishes, and opens to an inviting living and dining room spaces filled with natural light, while the first-floor bathroom addition adds convenience and versatility. Featuring new appliances, custom cabinetry, updated flooring, and the rare convenience of a first-floor full bathroom. Thoughtful details like stylish lighting, built-ins, and modern finishes enhance both form and function throughout the home. Upstairs, unwind in a spa-inspired bathroom complete with a sleek floating vanity, offering a true retreat feel. Step outside to a beautifully landscaped backyard with a cedar pergola and ann oversized deck ideal for gatherings or quiet mornings. Another standout feature is the professionally designed 960-square-foot studio space; ideal for a home office, creative workspace, fitness area, additional entertaining space or 2 car garage. It is fully insulated, heated and cooled! Other recent improvements include fresh exterior paint, an updated electrical panel, new floors, inlet lighting/switches. Significant upgrades to the detached two-car garage, including new concrete garage floor/apron and a brand-new garage door installed in 2026. The spacious backyard provides plenty of room for entertaining, gardening, or simply enjoying Michigan summers. Located within walking distance of Royal Oak's award-winning restaurants, shopping, nightlife, parks, and community events, this move-in-ready home offers a rare opportunity to enjoy city living with space and flexibility. Schedule your private showing today discover everything 1036 Irving Avenue has to offer.`,
    url: "https://www.zillow.com/homedetails/1036-Irving-Ave-Royal-Oak-MI-48067/24649092_zpid/",
    mlsListingId: "20261016511",
    weekends: ["jul10"],
  },
];

// List of available weekends for the dropdown, most recent first.
// start/end (ISO dates, inclusive) let the "open house next weekend"
// filter figure out which of these is the upcoming one relative to today.
const WEEKENDS = [
  { id: "jul31", label: "July 31–Aug 2", start: "2026-07-31", end: "2026-08-02" },
  { id: "jul24", label: "July 24–26", start: "2026-07-24", end: "2026-07-26" },
  { id: "jul10", label: "July 10–12", start: "2026-07-10", end: "2026-07-12" },
];
